# Generated by Django 5.0 on 2023-12-13 23:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_cadastro_usuarios', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Usuarios',
            new_name='Usuario',
        ),
        migrations.RenameField(
            model_name='usuario',
            old_name='id_usuarios',
            new_name='id_usuario',
        ),
    ]
